//! 一支**假的 coding agent CLI**，只給 `agent_probe` 與 `--verify` 用。
//!
//! 為什麼要它：測試**不可以啟動真的 claude／codex**（會用掉使用者的額度、會碰到真的登入狀態，
//! 而且它們的畫面時序沒辦法在自動測試裡穩定重現）。這支程式只做真正的 agent 在信箱流程裡
//! 一定會做的四件事：
//!
//! 1. 印一個提示字元（讓 `agent_ready` 看到「CLI 啟動後有畫過東西」）
//! 2. 從 stdin 讀一行
//! 3. 那一行裡有信箱路徑（`.ai/bus/NNNN-…md`）就**回一封信**到同一個信箱
//! 4. 印一行回應（讓畫面有輸出，忙 → 閒的轉換看得到）
//!
//! 用法（`--role-file` 是為了吃掉 Claude Code 那個旗標，內容會印出來當證據）：
//! ```text
//! fake_agent --id Agent-11 [--append-system-prompt-file <path>] [--ready-delay-ms 0]
//! ```
//!
//! ⚠️ 它**只寫自己被指定的那個信箱**（工作目錄底下的 `.ai/bus`），而且工作目錄一律由呼叫端
//! 設在 `%TEMP%`。不碰使用者真的 `.ai/`。

use std::io::{BufRead, Write};
use std::path::{Path, PathBuf};

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let flag = |name: &str| -> Option<String> {
        args.iter()
            .position(|a| a == name)
            .and_then(|i| args.get(i + 1))
            .cloned()
    };
    let role_file = flag("--append-system-prompt-file");
    // 真的 agent 是從角色檔知道自己是誰的（`Agent ID: Agent-12`），所以沒給 `--id` 時照做。
    // 兩格都以為自己是 Agent-11 的話回信會寄錯人（--verify 實際抓到）。
    let id = flag("--id")
        .or_else(|| role_file.as_deref().and_then(id_from_role_file))
        .unwrap_or_else(|| "Agent-11".to_string());
    let bus = std::env::current_dir()
        .unwrap_or_else(|_| PathBuf::from("."))
        .join(".ai")
        .join("bus");

    let mut out = std::io::stdout();
    // 啟動訊息：證明角色檔真的被交下來了（Claude Code 走旗標、OpenCode／Gemini 走打字）
    let _ = writeln!(out, "fake-agent {id} ready");
    match role_file.as_deref() {
        Some(p) => {
            let text = std::fs::read_to_string(p).unwrap_or_default();
            let ctx = text.contains("# Runtime Context (generated by AwayTerminal)");
            let me = text.contains(&format!("Agent ID: {id}"));
            let _ = writeln!(
                out,
                "role-file={} bytes={} runtime-context={ctx} my-id={me}",
                p,
                text.len()
            );
        }
        None => {
            let _ = writeln!(out, "role-file=none");
        }
    }
    let _ = write!(out, "{id}> ");
    let _ = out.flush();

    let stdin = std::io::stdin();
    let mut lines = stdin.lock().lines();
    while let Some(Ok(line)) = lines.next() {
        let line = line.trim().to_string();
        if line.is_empty() {
            let _ = write!(out, "{id}> ");
            let _ = out.flush();
            continue;
        }
        let _ = writeln!(out, "\r\n[{id}] got: {line}");
        if line.eq_ignore_ascii_case("exit") {
            let _ = writeln!(out, "[{id}] bye");
            let _ = out.flush();
            return;
        }
        // 投遞的那一行裡有信箱路徑 → 回一封信給寄件人（＝真的 agent 會做的事）
        if let Some(rel) = find_bus_path(&line) {
            match reply_to(&bus, &rel, &id) {
                Some(name) => {
                    let _ = writeln!(out, "[{id}] replied {name}");
                }
                None => {
                    let _ = writeln!(out, "[{id}] could not reply to {rel}");
                }
            }
        }
        let _ = write!(out, "{id}> ");
        let _ = out.flush();
    }
}

/// 角色檔裡的 `Agent ID: Agent-12` 那一行。
fn id_from_role_file(path: &str) -> Option<String> {
    let text = std::fs::read_to_string(path).ok()?;
    for line in text.lines() {
        if let Some(v) = line.strip_prefix("Agent ID:") {
            let v = v.trim();
            if !v.is_empty() {
                return Some(v.to_string());
            }
        }
    }
    None
}

/// 從投遞那一行裡挑出 `.ai/bus/NNNN-…-to-…md`（各語言的句子都能用：只看路徑長相）。
fn find_bus_path(line: &str) -> Option<String> {
    for token in line.split_whitespace() {
        let t = token.trim_matches(|c: char| !(c.is_ascii_alphanumeric() || "./-_".contains(c)));
        if t.contains(".ai/bus/") && t.ends_with(".md") {
            return Some(t.to_string());
        }
    }
    // 中文句子沒有空白分隔（「請讀 .ai/bus/0001-….md，依你的角色」）→ 直接找片段
    let start = line.find(".ai/bus/")?;
    let rest = &line[start..];
    let end = rest.find(".md")? + 3;
    Some(rest[..end].to_string())
}

/// 回一封 `TASK_RESULT` 給那封信的寄件人。回傳新檔名。
fn reply_to(bus: &Path, rel: &str, me: &str) -> Option<String> {
    let name = Path::new(rel).file_name()?.to_string_lossy().to_string();
    let path = bus.join(&name);
    let text = std::fs::read_to_string(&path).ok()?;
    let from = header(&text, "from").unwrap_or_else(|| "Agent-11".to_string());
    let task = header(&text, "task").unwrap_or_default();

    // 編號＝資料夾裡最大的 NNNN + 1（和 AwayTerminal 教 agent 的規則一樣）
    let mut max = 0u32;
    if let Ok(rd) = std::fs::read_dir(bus) {
        for e in rd.flatten() {
            let n = e.file_name().to_string_lossy().to_string();
            if let Some(num) = n.get(..4).and_then(|p| p.parse::<u32>().ok()) {
                max = max.max(num);
            }
        }
    }
    let out_name = format!("{:04}-{me}-to-{from}.md", max + 1);
    let body = format!(
        "---\nfrom: {me}\nto: {from}\ntype: TASK_RESULT\ntask: {task}\nstatus: completed\n---\n\
fake-agent {me} handled {name}.\n"
    );
    std::fs::write(bus.join(&out_name), body).ok()?;
    Some(out_name)
}

fn header(text: &str, key: &str) -> Option<String> {
    for line in text.lines().take(20) {
        if let Some(v) = line.strip_prefix(&format!("{key}:")) {
            let v = v.trim();
            if !v.is_empty() {
                return Some(v.to_string());
            }
        }
    }
    None
}
